name: Testes Automatizados

on:
  workflow_dispatch:  # Aciona a pipeline manualmente

jobs:
  testes:
    runs-on: ubuntu-latest
    env: # Defina as variáveis de ambiente aqui
      CHROMEDRIVER_PATH: /Users/carolinacosta/Documents/chromedriver/chromedriver

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Executar testes
      run: |
        export PATH=$PATH:$CHROMEDRIVER_PATH
        pytest
