name: Testes Automatizados

on:
  workflow_dispatch:  # Aciona a pipeline manualmente

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Iniciar contêiner do Selenium Hub
      run: |
        docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:latest

    - name: Iniciar contêiner do nó do Chrome
      run: |
        docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
          --shm-size="2g" \
          -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
          -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
          selenium/node-chrome:latest

    - name: Executar testes
      run: |
        pytest

    - name: Parar contêineres do Selenium
      run: |
        docker stop selenium-hub
        docker stop $(docker ps -a -q --filter ancestor=selenium/node-chrome)

    - name: Parar contêineres remanescentes
      run: |
        docker rm $(docker ps -a -q)
