name: Testes Automatizados

on:
  workflow_dispatch:  # Aciona a pipeline manualmente

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Gere o ChromeDriver
      run: |
        wget -O chromedriver-linux64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        mv chromedriver-linux64/chromedriver /tmp/
      working-directory: ${{github.workspace}}

    - name: Configurar ChromeDriver
      uses: actions/upload-artifact@v2
      with:
        name: chromedriver
        path: /tmp/chromedriver-linux64/chromedriver

    - name: Imprimir diretório atual
      run: |
        pwd
      working-directory: ${{github.workspace}}

    - name: Executar testes
      run: |
        pytest
